apiVersion: v1
kind: Service
metadata:
  name: seafile
  namespace: app-internal
spec:
  selector:
    app: seafile
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
